name: test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make install-test
      - name: Lint
        run: make lint

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make install-test
    - name: Run tests
      run: |
        # export SSL_CERT_FILE so ClientEncryption object can encrypt/decrypt in test environment
        export SSL_CERT_FILE=$(pwd)/tests/localhost.crt
        pytest

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make install-test
      - name: Generate coverage report
        run: |
          # export SSL_CERT_FILE so ClientEncryption object can encrypt/decrypt in test environment
          export SSL_CERT_FILE=$(pwd)/tests/localhost.crt
          pytest --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          token: 1455e721-304d-43a9-b346-bcdacfac6631
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
